name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Java (includes Maven if you set up caching)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # optional caching of Maven deps

      # Step 1: Build the project (compiles code + runs default tests)
      - name: Build with Maven
        run: mvn -B clean install

      # Step 2: Run only MobileRunner test
      - name: Run MobileRunner
        run: mvn -Dtest=MobileRunner test
