name: Daily Build and Test

on:
  # Scheduled run (midnight UTC)
  schedule:
    - cron: "0 0 * * *"

  # Manual trigger
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # OpenJDK distribution
          java-version: '17'      # Specify the required Java version

      # Step 3: Compile the Java file
      - name: Compile MobileRunner.java
        run: javac src/test/java/MobileRunner.java

      # Step 4: Run the Java file
      - name: Run MobileRunner
        run: java -cp src/test/java/MobileRunner.java
